//! フロントエンドから `invoke` で呼べるコマンド。

use crate::activity::LogEntry;
use crate::checks;
use crate::http::Http;
use crate::importers;
use crate::knowledge::{self, JavaRule, KnowledgeStore, MergeSummary, RuleKey, SharedFile};
use crate::model::{CheckOptions, CheckProgress, CheckResult, Component, Ecosystem, ImportResult, JavaRequirement};
use crate::sources::{self, DataSourceView};
use std::path::PathBuf;
use std::sync::Arc;
use tauri::{AppHandle, Emitter, State};

#[tauri::command]
pub async fn import_file(http: State<'_, Http>, path: String) -> Result<ImportResult, String> {
    let p = path.clone();
    let result = tauri::async_runtime::spawn_blocking(move || importers::import_file(&PathBuf::from(p)))
        .await
        .map_err(|e| e.to_string())?;
    match &result {
        Ok(r) => http.log().info(tr!("取り込み: {path}（{}、{} 件）", "Imported: {path} ({}, {} components)", r.format, r.components.len())),
        Err(e) => http.log().info(tr!("取り込み失敗: {path}: {e}", "Import failed: {path}: {e}")),
    }
    result
}

/// pom.xml のあるプロジェクトで Maven を実行して SBOM を生成し、取り込む。
#[tauri::command]
pub async fn generate_sbom_with_maven(
    http: State<'_, Http>,
    pom_path: String,
    options: CheckOptions,
) -> Result<ImportResult, String> {
    if !options.source_enabled(sources::MAVEN_LOCAL) {
        return Err(tr!(
            "データソース「ローカルの Maven」が設定で無効になっています。",
            "The data source \"Local Maven\" is disabled in the settings."
        ));
    }
    let http = http.inner().clone();
    tauri::async_runtime::spawn_blocking(move || {
        let bom = importers::maven::generate_sbom(&PathBuf::from(&pom_path), http.log())?;
        let mut result = importers::import_file(&bom)?;
        result
            .warnings
            .insert(0, tr!("{pom_path} から Maven で生成した SBOM（{}）です。", "SBOM generated by Maven from {pom_path} ({}).", bom.display()));
        Ok(result)
    })
    .await
    .map_err(|e| e.to_string())?
}

/// チェックを実行する。進捗は `check-progress` イベントで通知する。
#[tauri::command]
pub async fn run_checks(
    app: AppHandle,
    http: State<'_, Http>,
    components: Vec<Component>,
    options: CheckOptions,
) -> Result<Vec<CheckResult>, String> {
    http.configure(&options);
    let progress: checks::ProgressFn = Arc::new(move |p: CheckProgress| {
        let _ = app.emit("check-progress", p);
    });
    let results = checks::run_checks(&http, &components, &options, progress).await;
    if let Err(e) = http.save().await {
        eprintln!("キャッシュを保存できませんでした: {e}");
    }
    Ok(results)
}

/// 指定バージョンに必要な Java を答える（Maven のみ）。ナレッジに記録があればそれを使い、
/// 無ければ Maven Central の jar から判定してナレッジに記録する。
#[tauri::command]
pub async fn java_requirements(
    http: State<'_, Http>,
    store: State<'_, KnowledgeStore>,
    component: Component,
    versions: Vec<String>,
    options: CheckOptions,
) -> Result<Vec<JavaRequirement>, String> {
    if component.ecosystem != Ecosystem::Maven {
        return Ok(Vec::new());
    }
    let Some(group) = component.group.as_deref() else { return Ok(Vec::new()) };
    http.configure(&options);
    let can_fetch = options.source_enabled(sources::MAVEN_CENTRAL);
    let shared = knowledge::load_shared(&options.shared_knowledge_files);
    let mut out = Vec::new();
    for v in versions {
        out.push(checks::java::resolve(&http, &store, &shared, group, &component.name, &v, can_fetch).await);
    }
    Ok(out)
}

#[derive(serde::Serialize)]
#[serde(rename_all = "camelCase")]
pub struct KnowledgeView {
    pub local_path: Option<String>,
    pub local_error: Option<String>,
    pub local: Vec<JavaRule>,
    pub shared: Vec<SharedFile>,
}

/// 手元と共有の Java 要件ナレッジ。
#[tauri::command]
pub fn knowledge_list(store: State<'_, KnowledgeStore>, shared_files: Vec<String>) -> KnowledgeView {
    KnowledgeView {
        local_path: store.path().map(|p| p.display().to_string()),
        local_error: store.load_error().map(str::to_string),
        local: store.entries(),
        shared: knowledge::load_shared(&shared_files),
    }
}

/// 手動の追加・修正。`original` は編集前の記録（対象を変えた場合に置き換える）。
#[tauri::command]
pub fn knowledge_upsert(
    http: State<'_, Http>,
    store: State<'_, KnowledgeStore>,
    rule: JavaRule,
    original: Option<RuleKey>,
) -> Result<(), String> {
    let unknown = tr!("不明", "unknown");
    let label = format!("{} → Java {}", rule.scope_label(), rule.java.as_deref().unwrap_or(&unknown));
    store.upsert(rule, original)?;
    http.log().info(tr!("Java 要件ナレッジを登録: {label}", "Java requirement registered: {label}"));
    Ok(())
}

#[tauri::command]
pub fn knowledge_delete(http: State<'_, Http>, store: State<'_, KnowledgeStore>, key: RuleKey) -> Result<bool, String> {
    let deleted = store.delete(&key)?;
    if deleted {
        http.log().info(tr!(
            "Java 要件ナレッジを削除: {}:{} {}",
            "Java requirement deleted: {}:{} {}",
            key.group,
            key.artifact,
            key.version.or(key.series).unwrap_or_default()
        ));
    }
    Ok(deleted)
}

/// 他のナレッジファイルを手元に取り込む（手元の手動記録は上書きしない）。
#[tauri::command]
pub fn knowledge_import(http: State<'_, Http>, store: State<'_, KnowledgeStore>, path: String) -> Result<MergeSummary, String> {
    let file = knowledge::KnowledgeFile::read(std::path::Path::new(&path))?;
    let summary = store.merge(file.entries)?;
    http.log().info(tr!(
        "Java 要件ナレッジを取り込み: {path}（追加 {}、更新 {}、手動記録と衝突して見送り {}）",
        "Java requirements imported from {path} (added {}, updated {}, skipped {} conflicting with manual records)",
        summary.added, summary.updated, summary.skipped
    ));
    Ok(summary)
}

/// 手元のナレッジを書き出す（共有用）。`include_detected` が false なら手動の記録だけ。
#[tauri::command]
pub fn knowledge_export(
    http: State<'_, Http>,
    store: State<'_, KnowledgeStore>,
    path: String,
    include_detected: bool,
) -> Result<usize, String> {
    let count = store.export(std::path::Path::new(&path), include_detected)?;
    http.log().info(tr!("Java 要件ナレッジを書き出し: {path}（{count} 件）", "Java requirements exported to {path} ({count} records)"));
    Ok(count)
}

/// 現在の表示言語でのデータソース一覧。
#[tauri::command]
pub fn data_sources() -> Vec<DataSourceView> {
    sources::SOURCES.iter().map(|s| s.view()).collect()
}

/// 表示言語（`ja` / `en`）。バックエンドが作るメッセージ・ログの言語もこれに従う。
#[tauri::command]
pub fn set_language(language: String) {
    crate::i18n::set_language(&language);
}

/// このセッションの通信・操作ログ（新しい記録は `activity-log` イベントでも届く）。
#[tauri::command]
pub fn activity_log(http: State<'_, Http>) -> Vec<LogEntry> {
    http.log().recent()
}

#[tauri::command]
pub fn log_directory(http: State<'_, Http>) -> Option<String> {
    http.log().dir().map(|d| d.display().to_string())
}

/// エクスポート用。保存先はフロントの保存ダイアログで利用者が選んだパスに限る。
#[tauri::command]
pub async fn save_text_file(path: String, contents: String) -> Result<(), String> {
    std::fs::write(&path, contents).map_err(|e| tr!("{path} に保存できません: {e}", "Cannot save {path}: {e}"))
}

#[tauri::command]
pub async fn clear_cache(http: State<'_, Http>) -> Result<(), String> {
    http.clear().await?;
    http.log().info(tr!("キャッシュを削除しました", "Cache cleared"));
    Ok(())
}
